# Intelligent Agriculture Workshop
:experimental:
:imagesdir: documentation/modules/ROOT/assets/images

## Overview

|===
|| 

|Audience Experience Level
|Beginner

|Average Time to Complete	
|60 minutes
|===

## Documentation

This workshop is based on link:https://antora.org/[Antora] and link:https://github.com/redhat-scholars/courseware-template[Red Hat scholars template] to build HTML based tutorials.


### Lab Parameters

This lab supports both link:site.yml#L17[Antora variables] than query parameters. Query params makes the workshop content dynamic, like URLs specific for your cluster to copy and paste.

NOTE: In the table above, CRC and Playground links use them.

Here's the list of all query params used (they are all optional, but generated links won't work unless at least `CLUSTER_SUBDOMAIN` is set):

[%header,cols=2*] 
|===
|PARAM
|Description

|`CLUSTER_SUBDOMAIN`
|The subdomain for your OpenShift cluster in the form `apps.<cluster_name>.<base_domain>`, e.g. `apps.openshift.mydomain.tld`

|`USERNAME`
| The username of your OpenShift cluster

|===

Example [Dev Mode]:

http://localhost:3000/intelligent-agriculture-workshop/main/1-introduction.html?USERID=user1&SUBDOMAIN=cluster-8s5ss.sandbox701.opentlc.com&TOMCATIP=150.240.99.53

## Deploy to OpenShift

[.console-input]
[source,bash]
----
oc new-app  https://github.com/RedHat-Middleware-Workshops/intelligent-agriculture-workshop.git --strategy=docker

oc create route edge intelligent-agriculture-workshop --service=intelligent-agriculture-workshop
----

## Contributing

Please refer to the link:CONTRIBUTING.adoc#contributing-guide[how to contribute] on how you can contribute to the tutorial.

 
